### ISSUE TITLE
 typeof concatenation with ||

### ISSUE THREAD

**Issue by canonex** [firebug/firebug#7913]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.7.0
Build ID: 20150513015018.
Confimed also on Windows 8.1, Firefox version 38.0.05.

**Steps to reproduce:**

**Step A**
Execute this lines in the console:
```javascript
var pippo = false;
if (typeof cH === 'undefined' || typeof cH.test === 'undefined') {
  console.log('check totale');
  scriviA = 'A';
}

if (typeof cH === 'undefined' || typeof test === 'undefined' || pippo == false) {
  console.log('check totalew');
  scriviB = 'B';
}

//console.log(pippo);
if (pippo != false) {
  console.log(scriviA);
  console.log(scriviB);
  console.log('end');
}
```

**Step B**
uncomment the commented console.log(pippo);

**Actual results:**

**Result A**
check totale
check totalew
"B"

**Result B**
check totale
check totalew
false

**Expected results of step "A" is;**
"check totale"
"check totalew"

I expect furthermore that results doesn't change because a console.log().

Thank you,
Rickyx

**Comment by SebastianZ** [comment]
`"B"` resp. `false` are the return values of the executed script, which is the value of the last executed statement of the script. See [my answer on Stack Overflow](http://stackoverflow.com/a/30573089/432681).

Unfortunately Firebug does not make this obvious. The Firefox DevTools show a little triangle to indicate that.

As Firebug 3 will integrate into the DevTools, this will be fixed with that release. Therefore I close this issue.

Sebastian

**Comment by canonex** [comment]
Just to link those two closed issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1172891
