### ISSUE TITLE
Edit variables don't work when execution is stopped

### ISSUE THREAD

**Issue by sdavidg** [firebug/firebug#7956]
It's the same problem described here: https://code.google.com/p/fbug/issues/detail?id=7550

Fb: 2.0.12
FF: 41.0.1

**Comment by fflorent** [comment]
Thanks for the report David. I am working in it.

Florent

**Comment by fflorent** [comment]
(technical note) : it looks like it fails to get the environments when the thread is paused, and that's the reason why we can see `Object { type="object" }` for the scopes. And that sounds because the associated actors can't be retrieved using `threadActor._pausedActor.get(actorId)` in `DebuggerLib.getObject()`. 

Tricky issue. Might be worth to bisect... 

ping @janodvarko do you have any clue?

Florent

**Comment by sdavidg** [comment]
Any advance?

**Comment by fflorent** [comment]
Honza will take the bug soon.

Florent

2015-11-04 9:37 GMT+01:00 David <notifications@github.com>:

**Comment by janodvarko** [comment]
Should be fixed now.

@fflorent: can you please verify?

Honza

**Comment by sdavidg** [comment]
It works fine, thanks
